"""Application configuration using Pydantic Settings."""

from functools import lru_cache
from pathlib import Path
from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    """Application settings with environment variable fallback."""

    # Project metadata
    PROJECT_NAME: str = "borus"
    VERSION: str = "0.1.0"
    DEBUG: bool = False

    # Groq LLM Configuration
    GROQ_API_KEY: str = Field(
        default="",
        description="API Key for Groq Cloud. Can also be set via GROQ_API_KEY env var.",
    )
    GROQ_MODEL: str = Field(
        default="openai/gpt-oss-120b",
        description="Groq model ID to use for answer generation (e.g. openai/gpt-oss-120b, openai/gpt-oss-20b, qwen/qwen3.6-27b).",
    )
    GROQ_TEMPERATURE: float = Field(
        default=0.2,
        description="Sampling temperature for LLM responses (lower means more deterministic).",
    )
    GROQ_MAX_TOKENS: int = Field(
        default=1024,
        description="Maximum tokens generated by the LLM.",
    )

    # Embedding Configuration (FastEmbed)
    EMBEDDING_MODEL: str = Field(
        default="BAAI/bge-small-en-v1.5",
        description="FastEmbed model name (downloaded and cached locally).",
    )

    # Vector Database Configuration (ChromaDB)
    CHROMA_PERSIST_DIRECTORY: str = Field(
        default="./data/chroma",
        description="Directory path where ChromaDB persists vector embeddings and index.",
    )
    COLLECTION_NAME: str = Field(
        default="backend_docs",
        description="ChromaDB collection name for indexed technical documents.",
    )

    # Ingestion & Chunking Settings
    DOCS_SOURCE_DIR: str = Field(
        default="./docs_source",
        description="Path to folder containing source Markdown documentation (.md).",
    )
    CHUNK_SIZE: int = Field(
        default=600,
        description="Target chunk size (in characters) when splitting markdown sections.",
    )
    CHUNK_OVERLAP: int = Field(
        default=80,
        description="Character overlap between consecutive chunks.",
    )
    TOP_K: int = Field(
        default=4,
        description="Number of most relevant chunks to retrieve for RAG context.",
    )

    # Server Configuration
    APP_HOST: str = "0.0.0.0"
    APP_PORT: int = 8000

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )

    @property
    def docs_path(self) -> Path:
        return Path(self.DOCS_SOURCE_DIR)

    @property
    def chroma_path(self) -> Path:
        return Path(self.CHROMA_PERSIST_DIRECTORY)


@lru_cache()
def get_settings() -> Settings:
    """Return a cached instance of application settings."""
    return Settings()
